# Dependencies
markdown:         kramdown
highlighter:      rouge

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed

# Permalinks
permalink:           pretty
relative_permalinks: false

# Setup
name:             aming27
title:            aming27
tagline:          'El blog de Alfonso Ming'
description:      'No tengo mechero pero en mi casa hay cerillas.'
url:              https://aming27.github.io/
baseurl:          /
icon:             '/assets/apple-touch-icon-144-precomposed.png'
locale:           es_es

author:
  name:           'Alfonso Ming'
  url:            https://twitter.com/alfonsoming
  email:          alfonsming@gmail.com
  twitter:        alfonsoming
  github:         aming27
  linkedin:       alfonsoming
 
  

paginate:         5
paginate_path:    'posts/page:num'

version:          2.1.0

github:
  repo:           https://github.com/aming27

future:           false
